### ISSUE TITLE
PDF size increased

### ISSUE THREAD

**Issue by aditya-dikonia** [xthiago/pdf-version-converter#18]
Thanks for this library, it's working very well but facing an issue. After changing the version from 1.7 to 1.4 my 393 KB pdf size converted into 35MB. Is there any solution of this issue.

**Comment by xthiago** [comment]
Hi @aditya-dikonia, thank you for reporting that.

We have merged the pull-request #13 recently that aims to do not compress the PDF file in conversion. I wonder if it caused the contrary effect (increasing the file size)?

Could you revert the following line and check the size of resulting file?

```php
// file: src/Converter/GhostscriptConverterCommand.php
protected $baseCommand = 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=%s -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=%s %s';
```

https://github.com/xthiago/pdf-version-converter/pull/13/files#diff-36026646d2f57a7a92346a13d2d3dd81L25

**Comment by aditya-dikonia** [comment]
@xthiago Thanks for the solutions, This is working fine.

**Comment by xthiago** [comment]
@aditya-dikonia Do we need to change that line? Could you attach an PDF example where the size was increased with the current implementation?

**Comment by pixxelfactory** [comment]
Hi, we have the same problem, we are converting 1.5+ files to 1.4, they go up from 100-500kb to 11 mb.
I've checked the conversion string, it's the one from the pull-request, i updated via composer to the latest version too... But the files still get really big... =/

**Comment by pippuccio76** [comment]
Problem not solved on last release, file from 800 KB become 450 MB from 1.7 to 1.3

**Comment by surabiattack** [comment]
> Problem not solved on last release, file from 800 KB become 450 MB from 1.7 to 1.3

Hi, i have same problem too, 5mb pdf go up to 600mb
